from pathlib import Path
import re, urllib.parse
p=Path('index.html')
s=p.read_text(encoding='utf-8')
css='''<style id="amva-v552-css">#nav{overflow-x:hidden;overflow-y:hidden}#nav button{flex:1 1 12.5%;min-width:0;max-width:none;padding:7px 2px;font-size:18px;line-height:1.05;white-space:nowrap;overflow:hidden}#nav button small{font-size:9px;line-height:1.1;white-space:nowrap;display:block;overflow:hidden;text-overflow:clip}@media(max-width:520px){#nav button{font-size:17px;padding:6px 1px}#nav button small{font-size:8px}}@media(max-width:390px){#nav button{font-size:16px;padding:5px 0}#nav button small{font-size:7.5px}}.round-separator{display:flex;align-items:center;gap:10px;margin:18px 0 8px;font-weight:800;color:#176b3a;font-size:15px}.round-separator:before,.round-separator:after{content:"";height:2px;background:#b8d5c3;flex:1;border-radius:2px}.round-separator span{background:#176b3a;color:#fff;border-radius:999px;padding:6px 12px;white-space:nowrap;box-shadow:0 1px 3px #0002}</style>'''
if 'id="amva-v552-css"' not in s:
    s=s.replace('</head>',css+'</head>',1)
svg='''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><rect width="512" height="512" rx="110" fill="#176b3a"/><circle cx="256" cy="256" r="205" fill="#fff"/><circle cx="256" cy="256" r="188" fill="#176b3a"/><circle cx="256" cy="256" r="132" fill="#fff"/><circle cx="256" cy="256" r="118" fill="#f4f7f5"/><path d="M256 105c-20 34-25 49-25 72 0 23 10 42 25 57 15-15 25-34 25-57 0-23-5-38-25-72z" fill="#f2b632"/><path d="M166 164c28-18 47-23 69-20 19 3 35 14 48 31-22 8-43 17-57 34-15-18-34-31-60-45z" fill="#2e9d61"/><path d="M346 164c-28-18-47-23-69-20-19 3-35 14-48 31 22 8 43 17 57 34 15-18 34-31 60-45z" fill="#ef4a3b"/><path d="M177 340c24 16 44 23 68 22 19-1 35-9 52-26-20-12-38-22-57-40-16 20-34 33-63 44z" fill="#49a7df"/><path d="M335 340c-24 16-44 23-68 22-19-1-35-9-52-26 20-12 38-22 57-40 16 20 34 33 63 44z" fill="#d54f8a"/><text x="256" y="286" text-anchor="middle" font-family="Arial,sans-serif" font-size="82" font-weight="900" fill="#1264ad">AMVA</text><circle cx="256" cy="256" r="205" fill="none" stroke="#fff" stroke-width="9"/></svg>'''
data='data:image/svg+xml;charset=UTF-8,'+urllib.parse.quote(svg,safe="-_.!~*'()")
s=re.sub(r'<header><img src="data:image/[^;]+;base64,[^"]+"', '<header><img src="'+data+'"', s, count=1)
a=s.find('function games(){'); b=s.find('\nfunction table(){',a)
if a>=0 and b>a:
    helper='''function gameCardHtml(g){return `<div class="game-meta"><span>${date(g.match_date)}${g.match_time?` • ${g.match_time}`:""}</span>${g.place?`<span>• ${esc(g.place)}</span>`:""}${(()=>{const ht=S.teams.find(t=>t.id===g.home_team_id);return (ht?.field_name||ht?.field_address)?`<span>• 🏟️ ${esc(ht.field_name||"Campo do mandante")}${ht?.field_address?`<br><small>📍 ${esc(ht.field_address)}${ht?.city?`, ${esc(ht.city)}`:""}</small>`:""}</span>`:""})()} ${(()=>{const ht=S.teams.find(t=>t.id===g.home_team_id);return (ht?.field_name||ht?.field_address||ht?.field_cep)?`<a class="field-map-btn" href="${mapsLink(ht)}" target="_blank" rel="noopener">📍 Localização do campo</a>`:""})()}</div><div class="matchline">${shield(S.teams.find(t=>t.id===g.home_team_id))}<span class="teamname">${esc(tn(g.home_team_id))}</span><span class=score>${g.status==="Final"?`${g.home_score??0} × ${g.away_score??0}`:"×"}</span><span class="teamname">${esc(tn(g.away_team_id))}</span>${shield(S.teams.find(t=>t.id===g.away_team_id))}</div><div class="referee-game">${g.referee_name?`⚖️ Árbitro: <b>${esc(g.referee_name)}</b>`:""}</div><div class="game-status">${esc(g.status==="Final"?"Finalizado":(g.status||"Agendado"))}</div>${(g.home_photo_url||g.referee_photo_url||g.away_photo_url)?`<div class="gamephotos three">${g.home_photo_url?`<img class="gamephoto" src="${g.home_photo_url}" alt="Foto do mandante" onclick="viewPhoto(this.src)">`:`<div class="photo-empty"></div>`}${g.referee_photo_url?`<img class="gamephoto referee-photo" src="${g.referee_photo_url}" alt="Foto do árbitro" onclick="viewPhoto(this.src)">`:g.referee_no_image?`<div class="photo-empty no-image-slot">Sem Registro de Imagem</div>`:`<div class="photo-empty"></div>`}${g.away_photo_url?`<img class="gamephoto" src="${g.away_photo_url}" alt="Foto do visitante" onclick="viewPhoto(this.src)">`:`<div class="photo-empty"></div>`}</div>`:""}${admin?`<div class=actions><button class="btn mini" data-editgame="${g.id}">✏️ Editar jogo</button>${g.status!=="Cancelado"?`<button class="btn mini danger" data-cancelgame="${g.id}">🚫 Cancelar jogo</button>`:`<button class="btn mini" data-reactivategame="${g.id}">↩️ Reativar jogo</button>`}${g.status!=="Cancelado"?`<button class="btn" data-result="${g.id}">${g.status==="Final"?"Alterar resultado":"Lançar resultado"}</button>`:""}</div>`:""}`}\n'''
    fn='''function games(){let fixedRound=admin?(localStorage.getItem("amva_fixed_round")||""):"";let a=[...S.games].sort((x,y)=>String(x.match_date).localeCompare(String(y.match_date))||((+x.round||999)-(+y.round||999)));let rounds=[...new Set(S.games.map(g=>g.round).filter(Boolean))].sort((a,b)=>a-b);if(fixedRound)a=a.filter(g=>String(g.round||"")===String(fixedRound));let lastRound=null;let html=a.map(g=>{let sep=g.round&&String(g.round)!==String(lastRound)?`<div class="round-separator"><span>⚽ Rodada ${esc(g.round)}</span></div>`:"";lastRound=g.round;return sep+`<div class="game" data-round="${g.round||''}">${gameCardHtml(g)}</div>`}).join("");return `<div class=card><h2>⚽ Jogos e Calendário</h2><div class=actions><select id=gf><option value="">${fixedRound?`Rodada fixa: ${fixedRound}`:"Todas as rodadas"}</option>${rounds.map(r=>`<option value="${r}" ${!fixedRound&&String(r)===String(window.gamesRoundFilter||"")?"selected":""}>Rodada ${r}</option>`).join("")}</select>${admin?`<button class=btn id=fixround>${fixedRound?`🔒 Rodada ${fixedRound} fixa`:"🔓 Fixar rodada"}</button><button class=btn id=newgame>+ Novo jogo</button>`:""}</div><div id=gameslist>${html||"<p class=muted>Nenhum jogo cadastrado.</p>"}</div></div>`}\n'''
    s=s[:a]+helper+fn+s[b:]
gs=s.find('function gameForm(id){'); ge=s.find('\nfunction resultForm',gs)
if gs>=0 and ge>gs:
    form='''function gameForm(id){let g=id?S.games.find(x=>x.id===id):null;let teamOpts=(selected)=>S.teams.map(t=>`<option value="${t.id}" ${t.id===selected?'selected':''}>${esc(t.name)} — ${esc(t.city||"")}</option>`).join("");modal(`<h2>${g?"✏️ Editar jogo":"Novo jogo"}</h2><form id=f><label>Data</label><input id=d type=date value="${g?.match_date||""}" required><label>Horário</label><div style="display:flex;gap:7px;align-items:center"><input id=h type=time value="${g?.match_time||"15:30"}" disabled style="flex:1"><button type="button" class="btn mini" id=changeTime>Alterar</button></div><small class=muted>Horário padrão: 15:30. Clique em Alterar para escolher outro horário.</small><label>Número da rodada</label><input id=rd type=number min=1 value="${g?.round??""}" placeholder="Ex.: 1" required><label>Mandante</label><select id=a>${teamOpts(g?.home_team_id)}</select><small id=homeFieldHint class=muted></small><label>Visitante</label><select id=b>${teamOpts(g?.away_team_id)}</select><label>Local</label><input id=l value="${esc(g?.place||"")}" placeholder="Será preenchido automaticamente pelo campo do mandante"><label>Árbitro da partida</label><input id=ref value="${esc(g?.referee_name||"")}" placeholder="Nome do árbitro"><div class=actions><button class=btn>${g?"Salvar alterações":"Salvar jogo"}</button><button type=button class="btn mini" onclick="closeModal()">Cancelar</button></div></form>`);const changeTime=document.querySelector('#changeTime');const h=document.querySelector('#h');changeTime.onclick=()=>{h.disabled=false;h.focus();try{h.showPicker()}catch(e){}};const updateHomeField=()=>{const ht=S.teams.find(t=>String(t.id)===String(a.value));const hint=document.querySelector('#homeFieldHint');if(ht?.field_name){l.value=ht.field_name;hint.innerHTML=`🏟️ Campo do mandante: <b>${esc(ht.field_name)}</b>${ht.field_cep?` • CEP ${esc(ht.field_cep)}`:""}`;}else{hint.textContent='O mandante ainda não possui campo cadastrado.';}};a.onchange=updateHomeField;updateHomeField();document.querySelector("#f").onsubmit=async e=>{e.preventDefault();if(a.value===b.value)return alert("Escolha equipes diferentes.");let ht=S.teams.find(t=>String(t.id)===String(a.value));let obj={match_date:d.value,match_time:h.value||"15:30",round:+rd.value||null,home_team_id:a.value,away_team_id:b.value,place:l.value.trim()||(ht?.field_name||"Campo a definir"),referee_name:ref.value.trim()||null};try{if(g){let q=await db.from("games").update(obj).eq("id",g.id);if(q.error)throw q.error;}else{let q=await db.from("games").insert(obj);if(q.error)throw q.error;}closeModal();await load();render();}catch(e){alert(e.message);}}}\n'''
    s=s[:gs]+form+s[ge:]
p.write_text(s,encoding='utf-8')
